### ISSUE TITLE
Lottery program came to an end ?

### ISSUE THREAD

**Issue by amalnathsathyan** [bro-n-bro/Bro_n_Bro-Wednesday#10]
As of the schema in `readme.md` , the lottery comes to an end by 2022-06-15. Is this still continuing, starting from Tour 1 ??

**Comment by bro-n-bro-99** [comment]
Unfortunately no :( the lottery has been finished for about a month ago, we had 4 tours / 12 rounds which as you mentioned per our readme file came to the end and we have announced all official numbers that we got from the lottery. This was one of a kind IBC Lottery and we will never see another the exact one, for now we are not planning on launcing any other lottery. So just stick to our social media and check for any updates if something change. 
Thank you for your interest!
