### ISSUE TITLE
Set up a permanent black list for the lottery

### ISSUE THREAD

**Issue by bro-n-bro-0** [bro-n-bro/Bro_n_Bro-Wednesday#4]
Leave as a comment the list of funds addresses + team main addresses which suppose to be excluded from the lottery

Leave (?) at the end of the address if confused about it

**Comment by bro-n-bro-2** [comment]
Team addresses: osmo14nzyt8wmx4g6zkeluelukamgsh5v4xgnnzn4j8
osmo1tqdvlku97p88z5ndf3jz55vnccmzgs8jla375r
osmo1cg79pj70mgl8xlum0rw5yy6enk9jszsrfyf8cx

OSMO: https://www.mintscan.io/osmosis/account/osmo1pvxhtre74l37p6y2rs2e8xyek75z7xlc7g2trt
NGM: https://www.mintscan.io/emoney/account/emoney1cpfn66xumevrx755m4qxgezw9j5s86qkan5ch8
STARS: https://www.mintscan.io/stargaze/account/stars139a4n6w6dhwv60dj2clgwm6r0q84gju28z9at0
https://www.mintscan.io/stargaze/account/stars15gp36gk6jvfupy8rc4segppa38lhm3helm5f8k
https://www.mintscan.io/stargaze/account/stars168efxgnh55vcgx83x90pw2fves9anw8kmnlsf5
https://www.mintscan.io/stargaze/account/stars1pu39c2nc6k6mc5yvp5qqpfccc5lxpghccx7ggl
https://www.mintscan.io/stargaze/account/stars1dpzvwefvm56scev2jpayk2xvjwg3r4yjpfrsxv (?)
https://www.mintscan.io/stargaze/account/stars1pyap57v77g55d4yz3yynkynfuju02x087cavnp (?)

**Comment by bro-n-bro-2** [comment]
Fund: https://www.mintscan.io/osmosis/account/osmo1gmc3y8scyx9nemnuk8tj0678mn4w5l78343qvh

Osmo val: https://www.mintscan.io/osmosis/account/osmo13tk45jkxgf7w0nxquup3suwaz2tx483xrsefl7
Juno val: https://www.mintscan.io/juno/account/juno1quqxfrxkycr0uzt4yk0d57tcq3zk7srmpdd4c7
Tick val:  https://ping.pub/microtick/account/micro13mkjrr578sxd7whex3mqru96vdt3tttwet6cq2
NGM val: https://www.mintscan.io/emoney/account/emoney149vyxd36kxpg46rralaw6eejv4d9daqckn2wt8
Bostrom val: https://cyb.ai/network/bostrom/contract/bostrom1ydc5fy9fjdygvgw36u49yj39fr67pd9mv67ety
Stars val: https://www.mintscan.io/stargaze/account/stars1y58hfnm90r4efhlydx0gavz57lvm7k6uhpzu20

**Comment by bro-n-bro-2** [comment]
Juno fund: https://www.mintscan.io/juno/account/juno190g5j8aszqhvtg7cprmev8xcxs6csra7xnk3n3
Gravity fund: https://www.mintscan.io/gravity-bridge/account/gravity1xyqtlquzgtumv496rvjnh6543daa7mkpkvjwd4

**Comment by bro-n-bro-2** [comment]
Juno big acc: https://www.mintscan.io/juno/account/juno1aeh8gqu9wr4u8ev6edlgfq03rcy6v5twfn0ja8

**Comment by bro-n-bro-2** [comment]
bostrom1g07gj9ph0r2hjx6ffqn8vl38u4agd5mpqx9m7f
bostrom1pntx8ql2v7cqxu05etg8c4v0r2vz7qnq9uqmpy
bostrom1gxhs5wzam5rlgf6cs0lkme400ut64d4ncpfs2h
bostrom1tr3eyy9l480pxjk0ygudwpfus7j8pgdljn09jm
bostrom1ttd4h585vgy29gj0xe0p338drvw9w4m4hzwj9p
bostrom1t3222ju7ssu58xsm3m2xw445p94cqn2qrex3vy
bostrom1w4tvyvf3hhpcwv9d4axa8n0mmj5d6ypvpq5mj6 
bostrom1s4wntr9selfaznc2ezjkwnwt2y0terx9tqpda3
bostrom1smtmk8fe3qhlwj3h7nynl6p42946qydzvgj9va
bostrom17a7xxqa4drnalvv7pkxrkxqer953fdke3ulwx4
bostrom1lvkzyfaqjn87cfl65a55nuqt8u6uhnyuvhp8kr


Bostrom dead souls.

**Comment by bro-n-bro-2** [comment]
gravity13l0z8wcsak6z04xvn0m3ayacvp5ngde2ffgjyv
gravity1heyxccc9z7at2hj9ecuygdy5cws9ty99853u7e

**Comment by bro-n-bro-2** [comment]
stars1zc0xspsrjv24krgmslxza4zqmtva4qjnr0j0j2
stars1xuvqqtpav938pskxzslwv6x9xvs3yg456ud32f
stars18vf0hrxedgj9v8zf4pengmz4d4c3gzngkx5k9z
stars1jmvdlyau9h52arp6s6836k7m8u6xkuf7qgz32f
stars17a0xkhvnavt3fx5rfkrq89gkt0genewqjng0wv
