### ISSUE TITLE
Create report lottery

### ISSUE THREAD

**Issue by bro-n-bro-0** [bro-n-bro/Bro_n_Bro-Wednesday#8]
Data from @bro-n-bro-0 
Post from @bro-n-bro-99

**Comment by bro-n-bro-0** [comment]
Numbers:
- Raffles 12
- The number of unique winners is 115
- Won NGM amount is 552.929995
- Won JUNO amount is  347.231996
- Won TICK amount is 7.443996
- Won STARS amount is 13209.448624
- Won GRAV amount is 1286.148294
- Won BOOT amount is 16496659150
- Won OSMO amount is 536.090497
- The won amount in USD by the current rate is 2222
- The won amount in USD by the average rate  from the lottery beginning is 11634

The top 5 winners are:
- osmo1uncwfa0p5sq2uaf8xazd9ndrrrhk8rhztxkchc
- osmo140ua06006u0gew8yst4s24df4enfa46c28s9fn
- osmo1679yrs8dmska7wcsawgy2m25kwucm3z0uxyaa3
- osmo1e2qur2pmzn5jtderg3p7hwck53ert72tv9uk2p
- osmo1mn23nz7zt4af8ds835yefrphrzaryks32l2snl

**Comment by bro-n-bro-99** [comment]
posted in quitter, twitter, tg
https://cyb.ai/ipfs/QmSJrRNseZKvBML6QADMA5Fx1TEdoHEGPQ4izFX8SzFMxc
